"""
CyberGuard v2.0 — Report Routes
"""
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from database import get_db, UserDB, VendorDB, AlertDB, LeakDB, ActivityLogDB, SecurityScoreDB, QuestionnaireDB, ReportDB
from schemas import ReportGenReq
from auth import get_uid
from helpers import grade, risk_level

router = APIRouter(prefix="/api/reports", tags=["reports"])


@router.get("/")
def list_reports(uid: int = Depends(get_uid), db: Session = Depends(get_db)):
    return {"reports": [{"id": r.id, "title": r.title, "type": r.type, "pages": r.pages, "date": r.created_at.strftime("%Y-%m-%d")} for r in db.query(ReportDB).order_by(ReportDB.created_at.desc()).all()]}


@router.post("/generate", status_code=201)
def gen_report(req: ReportGenReq, uid: int = Depends(get_uid), db: Session = Depends(get_db)):
    user       = db.get(UserDB, uid)
    vendors    = db.query(VendorDB).all()
    all_alerts = db.query(AlertDB).all()
    open_alerts = [a for a in all_alerts if a.status == "open"]
    leaks      = db.query(LeakDB).all()
    logs       = db.query(ActivityLogDB).order_by(ActivityLogDB.timestamp.desc()).limit(500).all()
    sc         = db.query(SecurityScoreDB).order_by(SecurityScoreDB.created_at.desc()).first()
    score      = sc.score if sc else 742
    now        = datetime.utcnow()
    org        = user.company if user else "N/A"
    analyst    = user.name if user else "Unknown"

    crit_v  = sum(1 for v in vendors if risk_level(v.score) == "critical")
    high_v  = sum(1 for v in vendors if risk_level(v.score) == "high")
    avg_v   = int(sum(v.score for v in vendors) / len(vendors)) if vendors else 0
    anom_ct = sum(1 for l in logs if l.is_anomaly)
    active_leaks = [l for l in leaks if l.status != "resolved"]
    total_creds  = sum(l.credentials for l in leaks)
    sev_counts = {k: sum(1 for a in open_alerts if a.severity == k) for k in ["critical", "high", "medium", "low"]}

    titles = {
        "security-posture":  f"Security Posture Report — {now.strftime('%B %Y')}",
        "vendor-risk":       f"Vendor Risk Assessment — {now.strftime('%B %Y')}",
        "executive-summary": f"Executive Security Summary — {now.strftime('%B %d, %Y')}",
        "incident":          f"Incident & Threat Report — {now.strftime('%B %Y')}",
        "compliance":        f"Compliance Status Report — {now.strftime('%B %Y')}",
    }
    title = titles.get(req.type, f"Security Report — {now.strftime('%B %Y')}")

    SEP  = "=" * 60
    SEP2 = "-" * 60

    if req.type == "vendor-risk":
        content  = f"CYBERGUARD — VENDOR RISK ASSESSMENT\n{SEP}\n"
        content += f"Generated : {now.strftime('%Y-%m-%d %H:%M UTC')}\n"
        content += f"Org       : {org}\nAnalyst   : {analyst}\nVendors   : {len(vendors)} monitored\n{SEP}\n\n"
        content += f"EXECUTIVE SUMMARY\n{SEP2}\nAverage vendor security score: {avg_v}/950\nCritical risk vendors : {crit_v}\nHigh risk vendors     : {high_v}\nLow risk vendors      : {sum(1 for v in vendors if risk_level(v.score)=='low')}\n\n"
        content += f"VENDOR DETAILS\n{SEP2}\n"
        for v in sorted(vendors, key=lambda x: x.score):
            bar = "█" * int(v.score/95) + "░" * (10-int(v.score/95))
            content += f"\n  {v.name}\n    Domain      : {v.domain}\n    Category    : {v.category}\n    Criticality : {v.criticality}\n    Score       : {v.score}/950  {bar}\n    Risk Level  : {risk_level(v.score).upper()}\n    Open Issues : {v.issues}\n    Trend       : {v.trend}\n"
        content += f"\n{SEP}\nGenerated by CyberGuard v2.0"

    elif req.type == "executive-summary":
        content  = f"CYBERGUARD — EXECUTIVE SECURITY SUMMARY\n{SEP}\n"
        content += f"Date      : {now.strftime('%B %d, %Y')}\nOrg       : {org}\nPrepared  : {analyst}\n{SEP}\n\n"
        content += f"KEY METRICS AT A GLANCE\n{SEP2}\n  Security Score    : {score}/950  (Grade: {grade(score)})\n  Open Alerts       : {len(open_alerts)}  ({sev_counts['critical']} critical)\n  Vendors Monitored : {len(vendors)}  ({crit_v} critical risk)\n  Active Data Leaks : {len(active_leaks)}  ({total_creds} credentials exposed)\n  ML Anomalies      : {anom_ct} detected in last 500 actions\n\n"
        content += f"RISK ASSESSMENT\n{SEP2}\n  The organisation's overall security posture is rated {grade(score)}\n"
        if sev_counts["critical"] > 0: content += f"  ⚠ URGENT: {sev_counts['critical']} critical alerts require immediate attention\n"
        if crit_v > 0: content += f"  ⚠ {crit_v} vendor(s) classified as CRITICAL risk by ML models\n"
        if active_leaks: content += f"  ⚠ {len(active_leaks)} active data leak(s) under investigation\n"
        content += f"\nTOP PRIORITY ALERTS\n{SEP2}\n"
        for a in sorted(open_alerts, key=lambda x: {"critical":0,"high":1,"medium":2,"low":3}.get(x.severity,4))[:5]:
            content += f"  [{a.severity.upper():<8}] {a.title}\n"
        content += f"\nRECOMMENDATIONS\n{SEP2}\n"
        recs = []
        if sev_counts["critical"]>0: recs.append("Immediately remediate all critical severity alerts")
        if crit_v>0: recs.append(f"Conduct security review for {crit_v} critical-risk vendor(s)")
        if active_leaks: recs.append("Rotate all exposed credentials and API keys immediately")
        if anom_ct>10: recs.append("Investigate ML-detected anomalies for potential insider threats")
        recs.append("Schedule quarterly vendor risk reassessment")
        recs.append("Enable DMARC enforcement policy on email domain")
        for i,r in enumerate(recs,1): content+=f"  {i}. {r}\n"
        content += f"\n{SEP}\nGenerated by CyberGuard v2.0"

    elif req.type == "incident":
        content  = f"CYBERGUARD — INCIDENT & THREAT REPORT\n{SEP}\n"
        content += f"Generated : {now.strftime('%Y-%m-%d %H:%M UTC')}\nOrg       : {org}\nPeriod    : Last 30 days\n{SEP}\n\n"
        content += f"ALERT SUMMARY\n{SEP2}\n  Total Alerts    : {len(all_alerts)}\n  Open            : {len(open_alerts)}\n  Acknowledged    : {sum(1 for a in all_alerts if a.status=='acknowledged')}\n  Resolved        : {sum(1 for a in all_alerts if a.status=='resolved')}\n\n  Severity Breakdown:\n"
        for sev in ["critical","high","medium","low"]: content += f"    {sev.upper():<10}: {sev_counts.get(sev,0)}\n"
        content += f"\nML-DETECTED ANOMALIES\n{SEP2}\n  Total anomalies detected : {anom_ct}\n"
        high_anom = [l for l in logs if l.is_anomaly and l.anomaly_score>0.8]
        content += f"  High confidence (>80%)   : {len(high_anom)}\n"
        if high_anom:
            content += f"\n  Top anomalous events:\n"
            for l in high_anom[:5]: content += f"    {l.timestamp.strftime('%Y-%m-%d %H:%M')}  {l.user_email:<30} {l.action:<20} from {l.ip_address}\n"
        content += f"\nDATA LEAKS\n{SEP2}\n"
        for l in leaks: content += f"  [{l.severity.upper()}] {l.title}\n    Source: {l.source} | Status: {l.status} | Credentials: {l.credentials}\n"
        ml_alerts = [a for a in all_alerts if a.source=="ml"]
        if ml_alerts:
            content += f"\nML-GENERATED ALERTS ({len(ml_alerts)} total)\n{SEP2}\n"
            for a in ml_alerts[:8]: content += f"  [{a.severity.upper()}] {a.title}\n    {a.description[:80]}\n"
        content += f"\n{SEP}\nGenerated by CyberGuard v2.0"

    elif req.type == "compliance":
        content  = f"CYBERGUARD — COMPLIANCE STATUS REPORT\n{SEP}\n"
        content += f"Generated : {now.strftime('%Y-%m-%d %H:%M UTC')}\nOrg       : {org}\n{SEP}\n\n"
        qs = db.query(QuestionnaireDB).all()
        content += f"QUESTIONNAIRE STATUS\n{SEP2}\n  Total      : {len(qs)}\n  Completed  : {sum(1 for q in qs if q.status=='completed')}\n  In Progress: {sum(1 for q in qs if q.status=='in_progress')}\n  Pending    : {sum(1 for q in qs if q.status=='pending')}\n\n"
        for q in qs:
            pct = round((q.answered/q.total)*100) if q.total>0 else 0
            bar = "█"*int(pct/10) + "░"*(10-int(pct/10))
            content += f"  {q.title}\n    Framework : {q.framework}\n    Progress  : {q.answered}/{q.total} ({pct}%) {bar}\n    Status    : {q.status.replace('_',' ').upper()}\n    Due       : {q.due_date or 'N/A'}\n\n"
        content += f"EMAIL SECURITY\n{SEP2}\n"
        dmarc_alert = any("DMARC" in a.title for a in all_alerts)
        content += f"  DMARC Policy : {'⚠ NOT ENFORCED' if dmarc_alert else '✓ OK'}\n"
        content += f"  SSL/TLS      : {'⚠ EXPIRING SOON' if any('SSL' in a.title for a in open_alerts) else '✓ OK'}\n\n"
        content += f"VENDOR COMPLIANCE\n{SEP2}\n"
        for v in vendors: content += f"  {v.name:<20} Risk:{risk_level(v.score).upper():<10} Score:{v.score}\n"
        content += f"\n{SEP}\nGenerated by CyberGuard v2.0"

    else:  # security-posture (default)
        content  = f"CYBERGUARD — SECURITY POSTURE REPORT\n{SEP}\n"
        content += f"Generated : {now.strftime('%Y-%m-%d %H:%M UTC')}\nOrg       : {org}\nAnalyst   : {analyst}\n{SEP}\n\n"
        bar = "█" * int(score/95) + "░" * (10-int(score/95))
        content += f"OVERALL SECURITY SCORE\n{SEP2}\n  {score}/950  {bar}  Grade: {grade(score)}\n\n"
        content += f"SUMMARY\n{SEP2}\n  Open Alerts       : {len(open_alerts)}\n    Critical        : {sev_counts['critical']}\n    High            : {sev_counts['high']}\n    Medium          : {sev_counts['medium']}\n    Low             : {sev_counts['low']}\n  Vendors Monitored : {len(vendors)} (avg score: {avg_v})\n  Active Data Leaks : {len(active_leaks)}\n  ML Anomalies      : {anom_ct}\n\n"
        content += f"VENDOR RISK SUMMARY\n{SEP2}\n"
        for v in sorted(vendors, key=lambda x: x.score): content += f"  {v.name:<20} {v.score}/950  {risk_level(v.score).upper():<10} Issues:{v.issues}\n"
        content += f"\nCRITICAL & HIGH ALERTS\n{SEP2}\n"
        for a in [x for x in open_alerts if x.severity in ("critical","high")]:
            content += f"  [{a.severity.upper()}] {a.title}\n    → {a.description[:100]}\n\n"
        if active_leaks:
            content += f"DATA LEAKS\n{SEP2}\n"
            for l in active_leaks:
                content += f"  [{l.severity.upper()}] {l.title} ({l.source})\n"
                if l.credentials: content += f"    Credentials exposed: {l.credentials}\n"
        content += f"\n{SEP}\nGenerated by CyberGuard v2.0"

    pages = max(3, len(content.split("\n")) // 25)
    r = ReportDB(title=title, type=req.type, pages=pages, content=content)
    db.add(r)
    db.commit()
    db.refresh(r)
    return {"id": r.id, "title": r.title, "type": r.type, "pages": r.pages, "date": r.created_at.strftime("%Y-%m-%d"), "content": content}


@router.get("/{rid}/download")
def download_report(rid: int, uid: int = Depends(get_uid), db: Session = Depends(get_db)):
    r = db.get(ReportDB, rid)
    if not r:
        raise HTTPException(404)
    return {"content": r.content, "title": r.title}


@router.delete("/{rid}")
def delete_report(rid: int, uid: int = Depends(get_uid), db: Session = Depends(get_db)):
    r = db.get(ReportDB, rid)
    if not r:
        raise HTTPException(404)
    db.delete(r)
    db.commit()
    return {"message": "Deleted"}
